spring:
  # db 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/ssgame_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    username: ssafy
    #    password: ssafy
    url: jdbc:mysql://j6a306.p.ssafy.io:3306/ssgame_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ssgame
    password: ssgame1234

  # jpa 설정
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  # 서버 자동 실행
  devtools:
    restart:
      enabled: true

  # 파일 업로드
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

# 로그
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: debug

jwt:
  secret: 123456789012345678901234567890123456789012345678901234567890
  expiration: 1296000000